# Generated by Django 6.0.4 on 2026-05-04 17:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('relationships', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='familyrelationship',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relationships_owned', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='familyrelationship',
            name='related_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relationships_related', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='familyrelationship',
            constraint=models.UniqueConstraint(fields=('owner', 'related_user'), name='unique_owner_related_user'),
        ),
    ]
