# Generated by Django 6.0.4 on 2026-05-06 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relationships', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='familyrelationship',
            name='relation_type',
            field=models.CharField(choices=[('father', 'Father'), ('mother', 'Mother'), ('brother', 'Brother'), ('sister', 'Sister'), ('spouse', 'Spouse'), ('son', 'Son'), ('daughter', 'Daughter'), ('husband', 'Husband'), ('wife', 'Wife'), ('parent', 'Parent'), ('child', 'Child'), ('sibling', 'Sibling'), ('other', 'Other')], max_length=30),
        ),
    ]
