# Generated by Django 6.0.4 on 2026-05-06 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='friendrequest',
            name='from_user',
        ),
        migrations.RemoveField(
            model_name='friendrequest',
            name='to_user',
        ),
        migrations.RemoveConstraint(
            model_name='friendship',
            name='unique_friendship_pair',
        ),
        migrations.RemoveConstraint(
            model_name='friendship',
            name='ordered_friendship_pair',
        ),
        migrations.DeleteModel(
            name='FriendRequest',
        ),
        migrations.DeleteModel(
            name='Friendship',
        ),
    ]
